### ISSUE TITLE
[MOD REQUEST] Paradise SPRX

### ISSUE THREAD

**Issue by Revan20033** [ohhsodead/Modio#46]
- Name: Paradise SPRX
- Category: Grand Theft Auto
- System Type: DEX/CEX/HEN
- Author: gopro_2027
- Version: N/A
- Description: Paradise is free due to the gta servers shutting down on the 16th its late but people can use it for singleplayer
- Links: https://paradisesprx.net/gta.html
----------------------- 
*Please include any other additional information we may need here.

**Comment by ohhsodead** [comment]
A note to self: user must still provide a key that's generated on their website.

**Comment by ohhsodead** [comment]
@Revan20033 I can't find the files for this menu. Do you still have them? Does it still work?

**Comment by Revan20033** [comment]
> @Revan20033 I can't find the files for this menu. Do you still have them? Does it still work?

It should let me check

**Comment by Revan20033** [comment]
Needs a new link I'll get it

**Comment by ohhsodead** [comment]
> Needs a new link I'll get it

Thanks.

**Comment by Revan20033** [comment]
> > Needs a new link I'll get it
> 
> Thanks.

https://www.mediafire.com/file/91d6gf733xlmr26/GTA_V_Paradise_Mod_Menu.zip/file



Try this

**Comment by ohhsodead** [comment]
> 
> https://www.mediafire.com/file/91d6gf733xlmr26/GTA_V_Paradise_Mod_Menu.zip/file
> 
> Try this

Do you know the version?

**Comment by ohhsodead** [comment]
Added to database. Just need to change the version once I know what it is.
