### ISSUE TITLE
[MOD REQUEST] SEMJASES SPRX

### ISSUE THREAD

**Issue by Revan20033** [ohhsodead/Modio#47]
Semjases is free due to GTA online shutting down on Dec 16th 2021 

- Name: SEMJASES SPRX
- Category: Grand Theft Auto 5
- System Type: DEX/CEX/HEN
- Author: TheRouLetteBoi
- Version: N/A
- Description: Semjases is free due to servers going down on gta on Dec 16th
- Links: https://cdn.discordapp.com/attachments/881149203575894107/916314626155741224/Semjases.zip
----------------------
*Please include any other additional information we may need here.

**Comment by ohhsodead** [comment]
A note to self: No key is required for this.

**Comment by ohhsodead** [comment]
Added to database.
